apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-postgres
  template:
    metadata:
      labels:
        app: inventory-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.10
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: inventory
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password1234
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-postgres
spec:
  selector:
    app: inventory-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP